name: CD

on:
  push:
    branches:
      - develop  # Or your default branch
      - feature/add-continuous-deployment 
  pull_request:
    branches:
      - develop  # Or your default branch
   

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        docker build -t gcr.io/$GCP_PROJECT_ID/dvdapi:v3 .
        docker push gcr.io/$GCP_PROJECT_ID/dvdapi:v3

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy dvdrestapiv3 --image gcr.io/$GCP_PROJECT_ID/dvdapi:v3 --platform managed --region europe-west1


